### ISSUE TITLE
How to do Bigram and Trigram topic modeling using gensim ?

### ISSUE THREAD

**Issue by RVKRM** [bhargavvader/personal#5]
Hi bhargav

Its was informative notebook about topic modeling and spacy.

I have doubt how to do trigram and trigram topic modeling 
```
texts = metadata['cleandata']
bigram = gensim.models.Phrases(texts)
```
example this gives lda output of - India , car , license , india , visit , visa

I want output as - India car license , Visit visa , indian hotel 

 This code gives Bigram using tfidf
```
def display_topics(model, feature_names, no_top_words):
    
    for topic_idx, topic in enumerate(model.components_):
        print("Topic:", (topic_idx))
        print(" ".join([feature_names[i]
        for i in topic.argsort()[:-no_top_words - 1:-1]]))


def tfidf_vectorizer(documents,total_features):

    #  TFIDF Vectorizer
    tfidf_vectorizer = TfidfVectorizer(max_features=total_features, stop_words='english',ngram_range=[2,2])
    tfidf = tfidf_vectorizer.fit_transform(documents)
    tfidf_feature_names = tfidf_vectorizer.get_feature_names()
    return tfidf_vectorizer,tfidf,tfidf_feature_names


def count_vectorizer(documents,total_features):

    #  Count Vectorizer
    tf_vectorizer = CountVectorizer(max_features=total_features, stop_words='english')
    tf = tf_vectorizer.fit_transform(documents)
    tf_feature_names = tf_vectorizer.get_feature_names()
    return tf_vectorizer,tf,tf_feature_names
```

My question is how to do in gensim trigram and bigram ?

Thanks in advance

**Comment by bhargavvader** [comment]
Hello @Rahulvks , you would have to transform your corpus to include bigrams and trigrams - the gensim page on [collocations](https://radimrehurek.com/gensim/models/phrases.html) should explain this in more detail.
A rough code sample would be:

```
bigram = gensim.models.Phrases(texts)
texts = [bigram[line] for line in texts]
```

Running it one more time should give you your trigrams.

**Comment by pjmnoble** [comment]
As an interesting side effect this will also yield some quadgrams too where two bigrams identified by the initial Phrases model form a quad-gram of two bigrams . . . Not a critical problem
