### ISSUE TITLE
Pydata: Stopwords not being removed, even after adding to my_stop_words

### ISSUE THREAD

**Issue by NHameleers** [bhargavvader/personal#6]
Following up on pydata Amsterdam, where we noticed that stopwords like "the" were not removed from the corpus. This seems to happen in the notebook text_analysis_tutorial_unrun as well as ..._run.

Also, the word '-PRON-' appears in the clusters, but it was unclear where it's coming from.

**Comment by bhargavvader** [comment]
Thanks for pointing this out! Figured out the problem - spaCy does not consider capitalised words as stop words, and -PRON- refers to a pronoun. Fixing both in the notebook!
